% Dati
% Data
function [ R_b,R_t,H,theta_in,theta_fin,epsilon_0,nu,sigma,n_chambers,...
           dz_0,n_sd,Z_sd,flag_geom_sp, ...
           taglia,n_sez,tol_R,tol_angle,n_ref_cyto,n_ref_id,...
           metodo_cyto,...
           flag_model,flag_model_disc,...
           cc_R_st, D_R_st, cc_G_st, D_G_st, cc_E_st, D_E_st,...
           n_step_R,mu,lambda,nu_RE,nu_RG,...
           k_E, k_GE, PDE_s, mode_time, mode_space, n_sample,...
           n_Phi, Phi,...
           norma_inf,...
           peak_delta,...
           plot_niagara, plot_pool, inspect,...
           t_fin, n_step_t, metodo_id, solver, downsample,...
           u_tent,v_tent,tol_stat,...
           theta, alpha, tol_fix,...
           beta_dark,k_st, B_ca, F, f_ca,...
           cc_u,kk_u,cc_v,kk_v,...
           alpha_max,alpha_min,m_cyc,k_cyc,...
           j_cg_max,m_cg,K_cg,...
           j_ex_sat,K_ex,...
           flag_Ca_clamp] = data( )  %These are new, not in old codes
%Output all parameters defining cone geometry.
%   


%%%%%%%%%%%%%%%%%%%%% CONE GEOMETRIC PARAMETERS %%%%%%%%%%%%%%%%%%%%%%%%%%%
%Radius at the bottom 
R_b=3; %R_rod=2.15% [\mu m]
%R_b = 3.1;
%Radius at the top
R_t=1; % [\mu m] Only used in cone scripts
%R_t = 1.2;
%Cone height
H=15; % [\mu m]
%H=12;
%The lambda(z) scaling (Careful lambda already used)
%lambda  = @(z) R_b/R_t - (R_b-R_t)/(H*R_t).*z;

%Number of physical interdiscal spaces to comprise COS. 
%%if a linear spacing is used (flag_geom_sp=false), n_sez must be greater 
%%than or equal to 1+2*n_sd (n_sd in the number of special discs)if a log 
%%spacing is used (flag_geom_sp=true), n_sec must be greater than or equal 
%%to 1+4*n_sd

n_chambers = 500;

%type of spacing between cross sections
%true=geometric progression of interspaces between cross sections, 
%starting a each special disc
%false=constant spacing between cross sections

flag_geom_sp=true;     %Not used in nonhomogenized

% step of longitudinal space discretization near a special disc
% may be taken equal to (1+nu)*epsilon_0, but in this way discretization 
%becomes crowded near special discs
dz_0=29e-3; % []        %Not used in nonhomogenized

% Sliver angular positions
theta_in=-pi/2; %-3*pi/2+pi/8;                     %Make sure theta_in preceedes theta_fin in 
theta_fin=pi/2; %pi/2-pi/8;                   %rectangular coords. Matters for telling matlab 
                                % which domain is left or right of curve. 
                                %Lines 91, 96, 111, 154-155, 161-162 of 
                                %pdegeom_disc_sliver encode sliver variability.

%%%%%%%%%%%%%%%%%%%%% MICROSTRUCTURAL PARAMETERS %%%%%%%%%%%%%%%%%%%%%%%%%%

% ratio between interdisc and disc thickness 
%nu=14.5/14.5; % []
nu=1; % []

% disc thickness
%epsilon_0=14.5e-3; %  [\mu m]
%epsilon_0 = .5;
% This value is determined by number of chambers 
% and the scaling factors by 
% eps0 = H/(n*(1+nu)) where n is number
% of biophysical -- outside domain -- 
% discs.
epsilon_0 = H/((n_chambers-1)*(1+nu)); %should be 15e-3

% ratio between outer-shell and disc thickness
%sigma=15/14.5; % []
sigma=15/15; % []
%%%%%%%%%%%%%%%%% DATA ON THE ACTIVATION PROCESS %%%%%%%%%%%%%%%%%%%%%%%%%%
% number of special discs
n_sd=10;%n_sd = 10;%n_sd = 25;% n_sd=99; %n_sd=32;

% position of the special discs wrt the basis: the length of Z_sd 
% must be n_sd
Z_sd = [0.4*H 0.42*H 0.44*H 0.46*H 0.48*H 0.5*H 0.52*H 0.54*H 0.56*H 0.58*H];
%Z_sd = [0.1*H 0.05*H 0.12*H 0.03*H 0.07*H 0.09*H 0.055*H 0.15*H 0.13*H 0.06*H];
%Z_sd=.4*H;
%Z_sd=[0.2*H 0.35*H 0.5*H];% 0.65*H 0.8*H]; % [\mu m]
if length(Z_sd)~=n_sd
    error('Z_sd must have n_sd components')
end

% Dark hydrolysis rate of cGMP
beta_dark=67;
%beta_dark = 656;

% Rate of hydrolysis of cGMP by light activated PDE
k_st=0.83; % [(\mu m)^3/molecole s] 

%%%%%%%%%%%%%%%%% SPACE DISCRETIZATION PARAMETERS %%%%%%%%%%%%%%%%%%%%%%%%%
%size of the elements generated by initmesh (before invoking refinemesh)
%taglia=R_b/4;        %mu M; taglia means "size"
taglia=.25; % [\mu m]           
%The homogenized code on a disc of Radius R_b makes elements
                      %the size of R_b/4.  Since my code meshes something
                      %of unit radius, I'm making it the element size be
                      %that scaled by homothety 1/R_b bc that's
                      %transformation carries one into the other.

%number of disc cross sections within the mesh used in a interdiscal space
n_sez = 4;


% linear tolerance of the grid for searching nodes
% two nodes are assumed to be the same if their distance is less than tol_R
tol_R=taglia/1000;   %mu M

% angular tolerance of the grid for searching nodes
tol_angle=2*pi/1000; % [rad]

% number of refinements of the mesh (number of times refinemesh is invoked)
% this refers to number of times a disk cross section is refined in
% building the 3d geometry. (See n_ref_id)
n_ref_cyto=1;

% number of refinements of the mesh for the diffusion problem on the 
% incised disc it must be greater than or equal to n_ref_cyto
n_ref_id=2;
if n_ref_id <= n_ref_cyto
   error('For main_id sd2sez to work, sd needs more refinements than cyto');
end
%%%%%%%%%%%%%%%%% TIME INTEGRATION PARAMETERS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%integration method
%first component: 0=ode method (slow); 1=theta method
%second component (only for theta): 0=no factorization; 
%1=LU factorization; 2=cholesky factorization 
%third component (only for theta and factorizations): 0=no permutation; 
%1=Symmetric minimum degree permutation; 2=Symmetric reverse Cuthill-McKee
%permutation integration method for the homogenized problem

%cytosol time integration options
metodo_cyto=[1, 1, 1];
if metodo_cyto(1) ~= 1
    error('In cytosol, the time integration must be theta method');
end

%disc time integration options
metodo_id=[1, 1, 1];

%type of built-in solver invoked if ode method is chosen
solver='ode45';

% theta-parameter of the theta-method
theta=0.5; % []

%relaxation parameter in the fixed-point iteration: it must be 0<alpha<=1
%(alpha=1 means no relaxation). Better to change this.
alpha=1; % []

%relative error on the fixed-point iteration of the homogenized problem 
tol_fix=1e-5; % []

%type of norm used to estimate convergence: (L^\infty (if true), or L^1 
%(if false))
norma_inf=false;

% flag for the construction method of delta
%   true: type M\V: exact, but negative densities may arise
%   false: type k*V: approximate, but always yield positive densities
peak_delta=false;

% final time
% t_fin=5;   % [s]
% t_fin=0.8; % [s]
t_fin=1.5;%1.5; % [s]
% t_fin=1;     %1.5; % [s]

% number of integration steps
% n_step_t=160;
% n_step_t=300;
n_step_t = 450; %R:160,2500,80,450,500 C:160,1000,80,150,500
% n_step_t=80;
% n_step_t=150;
% n_step_t=500;

% downsampling: save the solution at one time step each downsample time 
% steps useful to reduce the amount of memory required to store sol
% reconstruct by linear interpolation
downsample=1;

% downsample must divide n_step_t: accordingly, change n_step_t
n_step_t=downsample*ceil(n_step_t/downsample);

%%%%%%%%%%%%%%%%%%%% PLOT AND FLOW CONTROL OPTIONS %%%%%%%%%%%%%%%%%%%%%%%%
% plotting meshes if true 
plot_mesh=false;

% drawing nodal and element number on meshes if true
plot_num=false;

% drawing waterfall of particles if true (monte carlo) or distribution of 
% E* and R* solutions
plot_niagara=false;

% drawing pool and beep if true (random path) 
plot_pool =false;

% requesting to press keys during execution if =true, for the sake of 
% controlling outputs
inspect=false;

%%%%%%%%%INITIAL VALUES TO BE USED IN SEARCHING FOR THE STEADY STATE%%%%%%%
% trial cGMP value
u_tent=2;  % [\mu M]

% trial Ca2+ value
v_tent=0.4; % [\mu M]

% maximum unbalancing of fluxes allowed in the steady-state 
tol_stat=1e-8; % [(\mu m) (\mu M)/s = 10^(-9) mole/(m^2 s)]

%%%%%%%%%%%%%%%%%%%% CHOICE OF MODEL IN THE CYTOSOL %%%%%%%%%%%%%%%%%%%%%%%
% flag_model=1 3D homogenized model, flag_model=2 well stirred model with
% diffusion along z. flag_model=3 is completely well stirred.
flag_model=1;

% flag_Ca_clamp=false: standard model; flag_model=true: Calcium clamp model
flag_Ca_clamp=false;

%%%%%%%%%%%%%%%%%%% CHOICE OF DIFFUSION MODEL ON THE DISC %%%%%%%%%%%%%%%%%
% flag_model_disc=1 modello R*-->E*
% flag_model_disc=2 modello R*-->G*-->E*
flag_model_disc=2;

%%%%%%%%%%%%%%%%%%%%%%%%%%% DATA ON R* %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% decay rate of R*
% k_R=2.8; % [s^{-1}]
% k_R=6.7;
k_R=12.5;

% type of shuting off of R*
%   0=always on: k_R is not used; 
%   1=sudden shuting off in n_step_R steps, with deterministic 
%     transition times, specified in Phi{d}(3:end,j)
%   2=sudden shuting off, at a random instant obtained as the sum of 
%     n_step_R random intervals, each distributed according to an
%     exponential random law with average given by tau
%     the random instants are different for different R*
%     though their statistical distributions are identical
%   3=exponential decay:
%     set n=n_step_R, 
%     the mass of R* which underwent i-1 transitions, i=1..n, 
%     and thus is active in the i-th condition, R*_i, is:
%     [(n*t/tau)^{i-1}/(i-1)!] * exp(-n*t/tau), 
%     provided that the steps take, in the mean, the same time
%     (equal_step==true) otherwise, see check_exp_R_st.m
%     The script governing may be found in the id directory, script file is
%     diffusione_ipd_PDE. ACTUALLY ABOVE FORMULA IS INCORRECT! THIS METHOD
%     IN STANDARD CODE NOW USES A CONTINUOUS TIME MARKOV CHAIN FOR THESE.
%     BOTH METHOD 2 AND METHOD 3. See difusione_sd_PDE line 161.
% mode_time=0;
% mode_time=1;
% mode_time=2;
 mode_time=3;
 
% type of spreading of R*
%   0=fixed at location specified by Phi{d}(:,j), for disc d,
%     location j
%   1=random path with diffusivity D_R_st starting from location
%     Phi{d}(:,j), or randomly generated, depending on random_location
%   2=solution of the heat equation with diffusivity D_R_st 
%     and initial datum delta at location Phi{d}(:,j)
mode_space=0;
% mode_space=1;
% mode_space=2;

% number of steps required for a complete shut off of R*
% this parameter is used when mode_time==1,2,3
n_step_R=1;

%Generate the strings lambda, mu and nu_RG by the formulas given in Lixin.
%Note that lambda_i is the rate at which R* acquires an ith phosphate. mu_i
%is rate at which Arrestin quenches the ith phosphate state. nu_i is
%catalytic activity of R* to create more G-protein. Any reference to tau_i
%is the mean time a R* remains in the i-1 phosphorylated state (ie mean of
%s_i sojourn time). lambda_0 and mu_0 are given in units of molecules/s.
lambda_0=105;
%lambda_0 = 12.5;
%mu_0=60;
mu_0=12.5;
K_v=0.5;                    
%Exponential rate of decrease of catalytic 
                            %activity

%nu_RG_0=330*30/145;
nu_RG_0=125;

%mu=[0.0000; 0.0000; 0.0000; .7500; 9.0000; 9.0000; 9.0000];
%mu=[0 0 0 1 1 1 1];
mu=1;
%mu=[0.1 0.3 0.6 0.8 1 1 1];

mu=mu(1:n_step_R)*mu_0;
%mu=zeros(1,n_step_R);
lambda=lambda_0*(n_step_R-(1:n_step_R));
nu_RG=nu_RG_0*exp(-K_v*((1:n_step_R)-1));

if length(lambda)~=n_step_R||length(mu)~=n_step_R||length(nu_RG)~=n_step_R
        error('lambda must have n_step_R components')
end
% % %     if abs(det(vander(tau)))<1000*eps
% % %        error('Error in the data: in the case of different steps,...
% % %        no two equal step are allowed')
% % %     end

% rate of production of E* per R* per second
% this is a column vector with n_step_R components: indeed, at each
% phosphorylation level, the R* has a different catalytic activity
% used when flag_model_disc==1
% nu_RE=183*[1]; % [s^{-1}]
% nu_RE=170*[1]; % [s^{-1}]
% nu_RE=160*[1]; % [s^{-1}]
  nu_RE=125*ones(n_step_R,1);
% % nu_RE=4/3*183*[1; 1/2]; % [s^{-1}]
if size(nu_RE,1)~=n_step_R
    error('nu_RE must have n_step_R rows')
end

% rate of production of G* per R* per second
% this is a column vector with n_step_R components: indeed, at each
% phosphorylation level, the R* has a different catalytic activity
% used when flag_model_disc==2
% k1 in shraiman paper
% nu_RG=170*[1]; % [s^{-1}]
% nu_RG=60*[ones(n_step_R,1)];
% nu_RG=135*(1-0.12*[0:n_step_R-1]'); % [s^{-1}]
% nu_RG=215*[1; 1/2]; % [s^{-1}]
% nu_RG=4/3*183*[1; 1/2]; % [s^{-1}]

% areal capacity of R*
cc_R_st=1; % []

% diffusion coefficient of R*
% D_R_st=0.7;   % [(\mu m)^2/s]
% D_R_st=10;   % [(\mu m)^2/s]
% D_R_st=1.5;   % [(\mu m)^2/s]
D_R_st=1.5;   % [(\mu m)^2/s]

% number of position where fotoisomerizations occur on each special disc: 
% the length of n_Phi must be n_sd on each special disk at least one 
% position must be present
n_Phi=ones(1,10); %R:ones(1,32);[4,1]; C:ones(1,1);(1,25);(1,99)
% n_Phi=[1 1 1];%1;
% n_Phi = [1 1 1 1 1];
% n_Phi=[3];
% n_Phi=[4,1];
if length(n_Phi)~=n_sd
    error('n_Phi must have n_sd components')
end

% position and transition times for each location of photoisomerization, 
% for each special disk, are in the cell structure Phi
% Phi must have n_sd components Phi{s}, s=1..n_sd, one for each special 
% disc Phi{s} is a matrix with 2+n_step_R rows and n_Phi(s) columns, 
% one for each location of photoisomerization
% on each column there are: 
%   rho; theta, which are the polar coordinates of that location; 
%   note: (rho,theta) are used only when random_location==false
%   t_1, t_2, ... t_{n_step_R}, which are the transition times from one
%   state to the next of the n_step_R admissible states
%   note: these transition times are used only when mode_time=1 
% (deterministic sudden shutoff)

Phi=cell(1,n_sd);
% Phi(1)={[2*R/3; 1*pi/23; 1/k_R/2; 1/k_R]};
% Phi(1)={[2*R/3; pi; 1/k_R]};
% The positions of the photons in each special disc must all be assigned with
% reference to the disc of radius R_t which is then scaled to the 
% cone, internally, by other scripts.
 Phi(1)={[R_t*0; pi/2; cumsum(1./(lambda+mu))']};
Phi(2)={[R_t*0; pi/2; cumsum(1./(lambda+mu))']};
Phi(3)={[R_t*0; pi/2; cumsum(1./(lambda+mu))']};
Phi(4)={[R_t*0; pi/2; cumsum(1./(lambda+mu))']};
Phi(5)={[R_t*0; pi/2; cumsum(1./(lambda+mu))']};
Phi(6)={[R_t*0; pi/2; cumsum(1./(lambda+mu))']};
Phi(7)={[R_t*0; pi/2; cumsum(1./(lambda+mu))']};
Phi(8)={[R_t*0; pi/2; cumsum(1./(lambda+mu))']};
Phi(9)={[R_t*0; pi/2; cumsum(1./(lambda+mu))']};
Phi(10)={[R_t*0; pi/2; cumsum(1./(lambda+mu))']};

%  Phi(1)={[R_t*.5; pi/4; cumsum(1./(lambda+mu))']};
%  Phi(2)={[R_t*.25; 7*pi/6; cumsum(1./(lambda+mu))'] };
%  Phi(3)={[R_t*.8; 11*pi/6; cumsum(1./(lambda+mu))']};
%  Phi(4)={[R_t*.3; 4*pi/3; cumsum(1./(lambda+mu))']};
%  Phi(5)={[R_t*.1; pi/2; cumsum(1./(lambda+mu))']};
%  Phi(6)={[R_t*.05; 3*pi/2; cumsum(1./(lambda+mu))']};
%  Phi(7)={[R_t*.9; pi/12; cumsum(1./(lambda+mu))']};
%  Phi(8)={[R_t*.95; pi; cumsum(1./(lambda+mu))']};
%  Phi(9)={[R_t*.72; 5*pi/4; cumsum(1./(lambda+mu))']};
%  Phi(10)={[R_t*.386;5*pi/4; cumsum(1./(lambda+mu))']};

% Phi(1)={[[2*R_b/3; pi; cumsum(1./(lambda+mu))'] [2*R_b/3; pi;...
% cumsum(1./(lambda+mu))']]};
% Phi(2)={[[2*R_b/3; pi; cumsum(1./(lambda+mu))'] [2*R_b/3; pi;...
% cumsum(1./(lambda+mu))']]};
% Phi(3)={[[2*R_b/3; pi; cumsum(1./(lambda+mu))'] [2*R_b/3; pi;...
% cumsum(1./(lambda+mu))']]};
% Phi(4)={[[2*R_b/3; pi; cumsum(1./(lambda+mu))'] [2*R_b/3; pi;...
% cumsum(1./(lambda+mu))']]};
% Phi(5)={[[2*R_b/3; pi; cumsum(1./(lambda+mu))'] [2*R_b/3; pi;...
% cumsum(1./(lambda+mu))']] };

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%clear Phi
%Phi=cell(1,n_sd);
%Phi(1)={[2*R_t/3; pi; cumsum(1./(lambda+mu))']};
%Phi(2)={[.5*R_t;7*pi/8; cumsum(1./(lambda+mu))']};
%Phi(3)={[0;0; cumsum(1./(lambda+mu))']};
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if length(Phi)~=n_sd
    error('Phi must have n_sd components')
end
for s=1:n_sd
    if size(Phi{s},1)~=2+n_step_R
        error('Phi(s) must have 2+n_step_R rows')
    end
    if size(Phi{s},2)~=n_Phi(s)
        error('Phi(s) must have n_Phi(s) columns')
    end
end

% if true, the initial positions of photoisomeritazions is randomly chosen,
% different for each sample
 random_location=false;
% random_location=true;

%%%%%%%%%%%%%%%%%%%%%%%%%% DATA ON G* %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% production rate of E* per each G* per unit density (#/\mu m^2)of basal E
% k2 in shraiman paper
k_GE=1; % [\mu m^2/s]

% areal capacity of G*
% this is coefficient on u_t in
% heat equation.
cc_G_st=1; % []

% diffusion coefficient of G*
% D_G_st=2.2+1.5;   % [(\mu m)^2/s]
% D_G_st=1.5+0.7;%+1.5;  
% D_G_st=1.5;%+1.5;
D_G_st=2.2;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%% DATA ON E* %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%superficial density of total PDE
%note: subunit density is 2*PDE_s
%PDE_s=750;  % [molecole/(\mu m)^2]
PDE_s=1000; % [molecole/(\mu m)^2]

%rate of hydrolysis of cGMP by dark-activated PDE
%k_hyd=7e-5;  % [(\mu m)^3/(molecole s)]
%beta_dark=2.9;
% According to Shen (10) only beta_dark and the vol2surfR
% value needed on volumic cGMP concentration hydrolysis
% term
%k_hyd=0.5*nu*epsilon_0*beta_dark/PDE_s;  % [(\mu m)^3/(molecole s)]

%gamma_0= k_hyd*PDE_s;  %  [\mu m s^(-1)]

%rate of hydrolysis of cGMP by light-activated PDE
%k_st=0.9; % [(\mu m)^3/molecole s]

% areal capacity of E*
cc_E_st=1; % []

% diffusion coefficient of E*
% D_E_st=0.7+1.5+0.8;   % [(\mu m)^2/s]
D_E_st=1.2;%+0.5;   % [(\mu m)^2/s]
% D_E_st=5;  % [(\mu m)^2/s]
% D_E_st=10;  % [(\mu m)^2/s]

% decay rate of E*
% kh in shraiman paper
% k_E=0.64;%0.58;%(0.58+0.76)/2; % [s^{-1}]
% k_E=6;
%k_E=6.5;%*75/3.3;
k_E=18.5;%*75/3.3;
% nota: Shraiman dà 10
%  k_E=0.2;%(0.58+0.76)/2; % [s^{-1}]

%%%%%%%%%%%%%%% TYPE OF SOLUTION PDE VS MONTE CARLO %%%%%%%%%%%%%%%%%%%%%%%
% solution type for the incised-disc problem
%   true: Monte Carlo both for R* and for E*; in this case, neglect
%         mode_space: always random walk both for R* and E* (mode_space==1)
%         particles are always on or random shut off (mode_time==0,2)
%         only allowed when flag_model_disc==1
%   false:diffusion (PDE) for E* with exponential shut off
%         mode_space and mode_time determine the tretment of R*
MC_disk=false;

% if R* diffuse, they cannot suddenly shut off, neither randomly, neither
% deterministically
% if R* do a random walk, they cannot exponentially fade
% if MC_disk==true, it must be mode_space==1 and mode_time==0,2, 
%flag_model==1, flag_model_disc==1
if ((mode_space==2)&&((mode_time==1)||(mode_time==2))) || ((mode_space==1)&&(mode_time==3)) || ...
        ( (MC_disk) && ((mode_space~=1)||((mode_time~=0)&&(mode_time~=2))||(flag_model~=1)||(flag_model_disc~=1)))
    error('combination of MC_disk, mode_space, mode_time, flag_model not allowed')
end

% number of random samples
n_sample=1;
% n_sample=800;
if n_sample ~= 1
    error(['My sparse E_st conversion method and corrente'...
          'need a deterministic setting with n_sample=1']);
end
if (n_sample>1) && ~((mode_space==1)||(mode_time==2)||(random_location))
    error('random samples not necessary for a deterministic setting')
end

%%%%%%%%%%%%%%%%%%%% CYTOSOL DIFFUSION COEFFICIENTS %%%%%%%%%%%%%%%%%%%%%%%
% volumic cGMP capacity
cc_u=1; % []

% volumic cGMP diffusion coefficient
% kk_u=160;%(50+196)/2;%100;  % [(\mu m)^2/s] 
%%%%%%%kk_u=150;  % [(\mu m)^2/s] 
kk_u=120;

% volumic Ca2+ capacity
cc_v=1; % []

% volumic Ca2+ diffusion coefficient
kk_v=15;  % [(\mu m)^2/s] 

%%%%%%%%%%%%%%%%%%%%%%%% DATA ON CYCLASE %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% maximum rate of production of cGMP
% alpha_max=50; % [\mu M s^{-1}]
% alpha_max=76.5*17/17; % [\mu M s^{-1}]
alpha_max=1311; % [\mu M s^{-1}]

% minumum rate of production of cGMP
% alpha_min=0.02*alpha_max; % [\mu M s^{-1}]
%alpha_min=5.5*17/17; % [\mu M s^{-1}]
alpha_min=alpha_max/13.9; % [\mu M s^{-1}]

% Hill coefficient
% m_cyc=2; % []
%m_cyc=2; % []
m_cyc=2.45; % []

% half-maximum-activation concentration
% k_cyc=0.135; % [\mu M]
%k_cyc=0.129; % [\mu M]
k_cyc=0.1; % [\mu M]
% gamma_1=(alpha_max-alpha_min)*k_cyc^m_cyc*(1/2*nu*epsilon_0); 
% 
% beta_1=k_cyc; % [\mu M]
% 
% m=m_cyc;
% 
% cf1=alpha_min*(1/2*nu*epsilon_0); % [\mu M \mu m s^{-1}]

%%%%%%%%%%%%%%%%% COMMON DATA ON CALCIUM CHANNELS %%%%%%%%%%%%%%%%%%%%%%%%%
% The channels can be located on the sliver (zone 1), on the disc surface
% (zone 2) and in correndece of the folds of the membrane (zone 3)
% IF WANT TO CHANGE CHANNEL LOCATIONS WILL NEED TO GO TO ASSEMBLA
% AND FORCING_CYTO AND CHANGE THE MATRICES USED IN GLOBAL AND LOAD
% ASSEMBLY
% flag_ch=false(1,3);
% flag_ch(1)=true;
%flag_ch(2)=true;
%flag_ch(3)=true;

% buffer of Ca2+, here assumed to be constant
% B_ca=20; % []
B_ca=6.66; % []
% Faraday constant
F=96500/1e21; % [C / (\mu M (\mu m)^3)]

%%%%%%%%%%%%%%%%% DATA ON THE CGMP OPERATED CHANNEL %%%%%%%%%%%%%%%%%%%%%%%
% maximum exchange current
% j_cg_max=7000e-12; % [A]
%j_cg_max=3550e-12; % [A]
j_cg_max=2500e-12; % [A]

% fraction of cGMP-activated current given by Ca2+
% f_ca=0.17; % []
f_ca=0.33; % []

% Hill coefficient
m_cg=2.5; % []
%m_cg=3.5; % []

% half-maximum-activation concentration, here assumed to be constant
K_cg=20;%32; % [\mu M]

% c_2=j_cg_max*f_ca/(Sigma_rod*B_ca*F*2); % [\mu M \mu m s^{-1}]
% 
% d_2=K_cg;
% 
% k=m_cg;
% 

%%%%%%%%%%%%%%%%%%%% DATA ON Ca2+ EXCHANGER %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% exchange current at saturation
% j_ex_sat=17e-12; % [A]
% j_ex_sat=1.8e-12; % [A]
j_ex_sat=4.87e-12;  % [A]

% half-maximum-activation concentration
% K_ex=1.5; %[\mu M]
K_ex=1.6; %[\mu M]
%K_ex=1.2; %[\mu M]

% c_1=j_ex_sat/(Sigma_rod*B_ca*F); % [\mu M \mu m s^{-1}]
% 
% d_1=K_ex; % [\mu M]


end

